In [4]:
#1. Convert a 1-D array into a 2-D array with 3 rows.
import numpy as np

a1=np.array([1,2,3,4,5,6,7,8,9])

a2=a1.reshape(3,-1)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#2. Replace all odd numbers in the given array with -1

a1=np.array([0,1,2,3,4,5,6,7,8,9])
a1[a1%2!=0]=-1
a1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [10]:
#3. Find the positions of: elements in x where its value is 
#   more than its corresponding element in y, and elements in 
#   x where its value is equals to its corresponding element in y.

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater=np.where(x>y)
equal=np.where(x==y)

print(greater,equal)

(array([1, 2, 4, 5, 6, 7, 8, 9]),) (array([0]),)


In [25]:
#4. Extract the first four columns of this 2-D array.

a4= np.arange(100).reshape(5,-1)
a4[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [49]:
#1. Generate a 1-D array of 10 random integers. 
#   Each integer should be a number between 30 and 40 (inclusive).

a1=np.random.randint(30,41,10)
a1

array([40, 37, 36, 35, 32, 36, 34, 30, 33, 31])

In [50]:
#2. Consider the following matrices :
#   A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))
#   Write a python program to perform the following using Numeric Python (numpy).
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 10]])

B = np.array([[7, 8, 10],[4, 5, 6],[1, 2, 3]])

# i) Addition and Subtraction
C = A + B
E = A - B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAddition (C = A + B):")
print(C)

print("\nSubtraction (E = A - B):")
print(E)

# ii) Sum of elements
print("\nSum of all elements of Matrix A:")
print(np.sum(A))

print("\nSum of each column of Matrix B:")
print(np.sum(B, axis=0))

print("\nSum of each row of Matrix C:")
print(np.sum(C, axis=1))

# iii) Matrix multiplication
D = np.matmul(A, B)

print("\nProduct of A and B (D):")
print(D)

# iv) Sort the elements of Matrix C
E = np.sort(C, axis=None).reshape(C.shape)

print("\nSorted Matrix C (E):")
print(E)

# v) Transpose of Matrix E
T = E.T

print("\nTranspose of Matrix E:")
print(T)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Matrix B:
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]

Addition (C = A + B):
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

Subtraction (E = A - B):
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements of Matrix A:
46

Sum of each column of Matrix B:
[12 15 19]

Sum of each row of Matrix C:
[31 30 31]

Product of A and B (D):
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Sorted Matrix C (E):
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]

Transpose of Matrix E:
[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
